// AUTO-GENERATED by scripts/gen-committees.mjs — do not edit.
// Add a tenure by creating lib/data/committees/<YYYY>-<YY>.ts instead.
import type { CommitteeMember } from '@/lib/data/committee'
import { members as t2025_26 } from './2025-26'
import { members as t2024_25 } from './2024-25'
import { members as t2023_24 } from './2023-24'
import { members as t2023_23 } from './2023-23'
import { members as t2023_22 } from './2023-22'
import { members as t2023_21 } from './2023-21'
import { members as t2023_20 } from './2023-20'

export interface Tenure {
  id: string
  label: string
  members: CommitteeMember[]
}

/** Newest first. */
export const tenures: Tenure[] = [
  { id: '2025-26', label: '25/26', members: t2025_26 },
  { id: '2024-25', label: '24/25', members: t2024_25 },
  { id: '2023-24', label: '23/24', members: t2023_24 },
  { id: '2023-23', label: '23/23', members: t2023_23 },
  { id: '2023-22', label: '23/22', members: t2023_22 },
  { id: '2023-21', label: '23/21', members: t2023_21 },
  { id: '2023-20', label: '23/20', members: t2023_20 },
]
